

services:
  reverse_proxy:
    image: nginx:alpine
    container_name: reverse_proxy
    ports:
      - "80:80"

    volumes:
      - ./nginx/templates:/etc/nginx/templates:ro
      - ./public_html:/usr/share/nginx/html:ro
      - ./container_logs/nginx:/var/log/nginx
    environment:
      - NGINX_ENVSUBST_TEMPLATE_SUFFIX=.template
      - NGINX_PORT=80
      - NGINX_PROXY=http://application:3001
    depends_on:
      - application
    restart: unless-stopped

  application:
    image: wt1-express:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: verteilte-systeme-app
    ports:
      - "3001:3001"
    volumes:
      - ./:/home/node/
    command: npm start
    restart: unless-stopped
